-- latest ACTIVE template by name (same name, many versions OK):
-- SELECT id, name, title, content, format, version, created_at, updated_at
-- FROM templates
-- WHERE name = $1 AND status = 'ACTIVE'
-- ORDER BY version DESC
-- LIMIT 1;

CREATE TABLE templates (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL,

  name              VARCHAR(255) NOT NULL,
  status            VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',

  title             TEXT         NOT NULL, -- email subject / card title template
  content           TEXT         NOT NULL, -- body / Adaptive Card JSON template
  format            VARCHAR(30)  NOT NULL DEFAULT 'TEXT', -- HTML / JSON

  version           INTEGER      NOT NULL DEFAULT 1,

  CONSTRAINT uq_templates_name_version UNIQUE (name, version)
);

CREATE INDEX idx_templates_name_active ON templates (name, version DESC)
  WHERE status = 'ACTIVE';

INSERT INTO templates (name, status, title, content, format, version, updated_at)
VALUES (
  'airflow',
  'ACTIVE',
  'Airflow Task Failed',
  $card${
  "type": "AdaptiveCard",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.5",
  "msteams": { "width": "Full" },
  "body": [
    {
      "type": "TextBlock",
      "text": "🚨 Airflow Task Failed",
      "weight": "Bolder",
      "size": "Large",
      "color": "Attention"
    },
    {
      "type": "TextBlock",
      "text": "Task cần xử lý trên môi trường PRODUCTION",
      "isSubtle": true,
      "wrap": true,
      "spacing": "None"
    },
    {
      "type": "Container",
      "style": "attention",
      "spacing": "Medium",
      "items": [
        {
          "type": "TextBlock",
          "text": "Team: {{team}}",
          "weight": "Bolder",
          "wrap": true,
          "spacing": "Small"
        },
        {
          "type": "TextBlock",
          "text": "{{status}} - retry: {{try_number}}",
          "weight": "Bolder",
          "wrap": true
        }
      ]
    },
    {
      "type": "FactSet",
      "spacing": "Medium",
      "facts": [
        { "title": "DAG", "value": "{{dag_id}}" },
        { "title": "Task", "value": "{{task_id}}" },
        { "title": "Run ID", "value": "{{run_id}}" },
        { "title": "Start", "value": "{{start_date}}" },
        { "title": "Logical", "value": "{{logical_date}}" }
      ]
    },
    {
      "type": "TextBlock",
      "text": "MIS · Data Platform",
      "isSubtle": true,
      "size": "Small",
      "spacing": "Medium"
    }
  ],
  "actions": [
    {
      "type": "Action.OpenUrl",
      "title": "View Task Log",
      "url": "{{log_url}}"
    }
  ]
}$card$,
  'ADAPTIVE_CARD',
  1,
  now()
);

INSERT INTO templates (name, status, title, content, format, version, updated_at)
VALUES (
  'default',
  'ACTIVE',
  '[{{kind}}] {{source}}',
  '{{message}}',
  'TEXT',
  1,
  now()
);
