CREATE TABLE notifications (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at        timestamptz  NOT NULL DEFAULT now(),
  updated_at        timestamptz  NOT NULL,

  code              VARCHAR(50)  NOT NULL,

  name              VARCHAR(255) NOT NULL,
  status            VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',

  source            VARCHAR(50)  NOT NULL REFERENCES sources (code),
  target            VARCHAR(50)  NOT NULL REFERENCES targets (code),
  channel           VARCHAR(20)  NOT NULL REFERENCES channels (code),
  template_id       BIGINT       NOT NULL REFERENCES templates (id),

  metadata          JSONB        NOT NULL DEFAULT '{}'::jsonb,

  CONSTRAINT uq_notifications_code UNIQUE (code)
);

CREATE INDEX idx_notifications_source ON notifications (source);
CREATE INDEX idx_notifications_target ON notifications (target);
CREATE INDEX idx_notifications_channel ON notifications (channel);
CREATE INDEX idx_notifications_status ON notifications (status);
