-- One row is one event callers trigger by code.
-- level: INFO, WARN, ERROR, CRITICAL 

CREATE TABLE notifications (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at        timestamptz  NOT NULL DEFAULT now(),
  updated_at        timestamptz  NOT NULL,

  code              VARCHAR(50)  NOT NULL UNIQUE,
  name              VARCHAR(255) NOT NULL,
  description       VARCHAR(255),
  source_code       VARCHAR(50)  NOT NULL REFERENCES sources (code),

  level             VARCHAR(20)  NOT NULL DEFAULT 'INFO', -- INFO, WARN, ERROR, CRITICAL
  status            VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE'
);

INSERT INTO notifications (code, name, description, source_code, level, updated_at) VALUES
  (
    'AIRFLOW_TASK_FAILED',
    'Airflow task failed',
    'Task failure on Airflow',
    'AIRFLOW',
    'ERROR',
    now()
  ),
  (
    'ETL_JOB_FAILED',
    'ETL job failed',
    'Batch pipeline failure',
    'ETL',
    'ERROR',
    now()
  ),
  (
    'ETL_JOB_SUCCEEDED',
    'ETL job succeeded',
    'Batch pipeline success',
    'ETL',
    'INFO',
    now()
  ),
  (
    'GITLAB_MR_OPENED',
    'GitLab merge request opened',
    'Merge request opened',
    'GITLAB',
    'INFO',
    now()
  ),
  (
    'REVENUE_DAILY',
    'Daily revenue',
    'Daily revenue and metrics digest',
    'REVENUE',
    'INFO',
    now()
  );
