-- audit/history each time a source triggers POST /notification/notify
-- recipients JSON: snapshot from targets.metadata { "to": [...], "cc": [...], "bcc": [...] }

CREATE TABLE deliveries (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL,

  notification_id   BIGINT       NOT NULL REFERENCES notifications (id),
  correlation_id    VARCHAR(100) NOT NULL,

  level             VARCHAR(10)  NOT NULL,
  title             VARCHAR(255) NOT NULL,
  message           TEXT         NOT NULL,

  recipients        JSONB        NOT NULL DEFAULT '{}'::jsonb,
  payload           JSONB        NOT NULL DEFAULT '{}'::jsonb,
  metadata          JSONB        NOT NULL DEFAULT '{}'::jsonb,

  CONSTRAINT uq_deliveries_notification_correlation UNIQUE (notification_id, correlation_id)
);

CREATE INDEX idx_deliveries_created_at ON deliveries (created_at);
CREATE INDEX idx_deliveries_notification_id ON deliveries (notification_id);
