CREATE TABLE requests (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at        timestamptz  NOT NULL DEFAULT now(),
  code              VARCHAR(36)  NOT NULL,
  trace_id          VARCHAR(36)  NOT NULL,
  variables         JSONB        NOT NULL DEFAULT '{}'::jsonb
);

