-- Fan-out: one notification code delivers through one or more channels.
-- targets.channel_code must equal channel_code (enforced in the service).
-- Template format: MSTEAMS → ADAPTIVE_CARD, EMAIL → TEXT or HTML, WEBHOOK → JSON.

CREATE TABLE notification_routes (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at        timestamptz  NOT NULL DEFAULT now(),
  updated_at        timestamptz  NOT NULL,

  notification_id   BIGINT       NOT NULL REFERENCES notifications (id),
  channel_code      VARCHAR(50)  NOT NULL REFERENCES channels (code),
  target_code       VARCHAR(50)  NOT NULL REFERENCES targets (code),
  template_id       BIGINT       NOT NULL REFERENCES templates (id),
  status            VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',

  CONSTRAINT uq_notification_routes UNIQUE (notification_id, channel_code, target_code),
  CONSTRAINT chk_notification_routes_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX idx_notification_routes_notification
  ON notification_routes (notification_id);

INSERT INTO notification_routes (
  notification_id, channel_code, target_code, template_id, updated_at
)
SELECT n.id, 'MSTEAMS', 'TEAM_MIS', t.id, now()
FROM notifications n
JOIN templates t ON t.name = 'airflow' AND t.version = 1 AND t.status = 'ACTIVE'
WHERE n.code = 'AIRFLOW_TASK_FAILED';

INSERT INTO notification_routes (
  notification_id, channel_code, target_code, template_id, updated_at
)
SELECT n.id, 'EMAIL', 'OPS_EMAIL', t.id, now()
FROM notifications n
JOIN templates t ON t.name = 'default' AND t.version = 1 AND t.status = 'ACTIVE'
WHERE n.code IN (
  'AIRFLOW_TASK_FAILED',
  'ETL_JOB_FAILED',
  'REVENUE_DAILY'
);

INSERT INTO notification_routes (
  notification_id, channel_code, target_code, template_id, updated_at
)
SELECT n.id, 'MSTEAMS', 'TEAM_MIS', t.id, now()
FROM notifications n
JOIN templates t ON t.name = 'default' AND t.version = 1 AND t.status = 'ACTIVE'
WHERE n.code IN ('ETL_JOB_FAILED', 'ETL_JOB_SUCCEEDED', 'GITLAB_MR_OPENED');

INSERT INTO notification_routes (
  notification_id, channel_code, target_code, template_id, updated_at
)
SELECT n.id, 'WEBHOOK', 'ORCHESTRATOR', t.id, now()
FROM notifications n
JOIN templates t ON t.name = 'default' AND t.version = 1 AND t.status = 'ACTIVE'
WHERE n.code IN ('ETL_JOB_SUCCEEDED', 'GITLAB_MR_OPENED');
