-- One rendered send. Same trace_id replayed for a route is a single row.
-- destination: snapshot of targets.metadata at send time.
-- status: QUEUED → SENT | FAILED (channel result).

CREATE TABLE deliveries (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at        timestamptz  NOT NULL DEFAULT now(),
  updated_at        timestamptz  NOT NULL,

  notification_id   BIGINT       NOT NULL REFERENCES notifications (id),
  route_id          BIGINT       NOT NULL REFERENCES notification_routes (id),
  trace_id          VARCHAR(100) NOT NULL,

  level             VARCHAR(20)  NOT NULL,
  title             VARCHAR(255) NOT NULL,
  body              TEXT         NOT NULL,

  destination       JSONB        NOT NULL DEFAULT '{}'::jsonb,
  variables         JSONB        NOT NULL DEFAULT '{}'::jsonb,
  status            VARCHAR(20)  NOT NULL DEFAULT 'QUEUED',

  CONSTRAINT uq_deliveries_route_trace UNIQUE (route_id, trace_id),
  CONSTRAINT chk_deliveries_level
    CHECK (level IN ('INFO', 'WARN', 'ERROR', 'CRITICAL')),
  CONSTRAINT chk_deliveries_status
    CHECK (status IN ('QUEUED', 'SENT', 'FAILED'))
);

CREATE INDEX idx_deliveries_created_at ON deliveries (created_at);
CREATE INDEX idx_deliveries_notification_id ON deliveries (notification_id);
