-- create in same transaction as deliveries on POST /notification/notify
-- outbox status: QUEUED -> PROCESSING -> SENT | FAILED
-- publisher polls QUEUED, marks PROCESSING, publishes to Kafka, then SENT (with offset) or FAILED

CREATE TABLE outbox (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL,

  notification_id   BIGINT       REFERENCES notifications (id),
  delivery_id       BIGINT       REFERENCES deliveries (id),
  correlation_id    VARCHAR(100) NOT NULL,

  topic             VARCHAR(255) NOT NULL,
  partition_key     VARCHAR(255) NOT NULL,
  "partition"       INT,
  "offset"          BIGINT,

  status            VARCHAR(20)  NOT NULL DEFAULT 'QUEUED',

  payload           JSONB        NOT NULL,
  error_message     TEXT,
  published_at      timestamptz
);

CREATE INDEX idx_outbox_queued ON outbox (created_at)
  WHERE status = 'QUEUED';

CREATE INDEX idx_outbox_notification_id ON outbox (notification_id);
CREATE INDEX idx_outbox_delivery_id ON outbox (delivery_id);
